name: nlp
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pytorch=1.9.0=py3.9_cuda10.2_cudnn7_0
  - python=3.9.6
  - ipykernel=5.3.4
  - scikit-learn=0.24.2
  - matplotlib=3.4.2
  - numpy=1.19.2
  - pandas=1.2.4
  - notebook=6.4.3
  - scipy=1.7.1 
  - seaborn=0.11.2
  - nb_conda_kernels=2.3.1
  - matplotlib=3.4.2
  - torchtext=0.10.0
  - nltk=3.6.2
  - pip==21.2.4
  - spacy-model-en_core_web_sm=3.0.0
  - torchvision=0.10.0
  - pip:
    - wget==3.2
    - zipfile36==0.1.3
    - torchsummaryX
    - spacy===3.1.1
    - spacy-legacy==3.0.8
    - setuptools==57.0.0
    - wheel==0.36.2